<a href="https://colab.research.google.com/github/AnkitSingh-12/numpy-lib/blob/main/PROJECT_OF_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROJECT**


In [ ]:
#
''' 1. Create Arrays:
o Create two NumPy arrays:
▪ A 1D array of 10 equally spaced values between 0 and 50.
▪ A 2D array of shape (3x3) containing random integers
between 5 and 20.'''

#▪ A 1D array of 10 equally spaced values between 0 and 50.
import numpy as np

arr = np.linspace(0, 50, 10)

print(arr)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
#▪ A 2D array of shape (3x3) containing random integers between 5 and 20
import numpy as np
arr = np.random.randint(5, 21, (3, 3))
print(arr)

[[12 17 18]
 [18  6 12]
 [15 16 17]]


In [ ]:
'''
2. Array Dimensions:
o Print the dimensions of both arrays.
o Print the shape of both arrays.

 '''
#o Print the dimensions of both arrays.
import numpy as np
arr_1 = np.linspace(0, 50, 10)
arr_2 = np.random.randint(5, 21, (3, 3))
print("Array 1 dimensions:", arr_1.ndim)
print("Array 1 shape:", arr_1.shape)
print("Array 2 dimensions:", arr_2.ndim)
print("Array 2 shape:", arr_2.shape)


# Print the shape of both arrays.
import numpy as np
arr_1 = np.linspace(0, 50, 10)
arr_2 = np.random.randint(5, 21, (3, 3))
print("Array 1 shape:", arr_1.shape)
print("Array 2 shape:", arr_2.shape)

Array 1 dimensions: 1
Array 1 shape: (10,)
Array 2 dimensions: 2
Array 2 shape: (3, 3)
Array 1 shape: (10,)
Array 2 shape: (3, 3)


In [ ]:
'''
3. Reshaping:
o Reshape the 1D array into a 2D array with shape (2x5).
o Print the reshaped array.
o Flatten the reshaped array back to 1D and print it.
'''
import numpy as np
arr_1d = np.linspace(0, 50, 10)
arr2d = arr_1d.reshape(2, 5)
print("Reshaped array:")
print(arr2d)
flattened_arr = arr2d.flatten()
print("Flattened array:")
print(flattened_arr)

Reshaped array:
[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]
Flattened array:
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
'''Part 2: Indexing and Slicing
4. Indexing:
o For the 2D array created in Part 1, print the element present at the
2nd row and 3rd column.
o Extract the first two rows and the last two columns of the array.'''

#o For the 2D array created in Part 1, print the element present at the 2nd row and 3rd column.
import numpy as np
a=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
print(a[1][2])

#Extract the first two rows and the last two columns of the array
import numpy as np
a=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
print(a[:2, 1:])

print(a[2, :])

print(a[:, 0])

6
[[2 3]
 [5 6]]
[7 8 9]
[1 4 7]


In [ ]:
'''
5. Slicing:
o Slice the first four elements from the flattened 1D array.
o Reverse the elements of the 1D array using slicing.

'''
#o Slice the first four elements from the flattened 1D array.
import numpy as np
arr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
flattened_arr = arr.flatten()
sliced_arr = flattened_arr[:4]
print(sliced_arr)

#o Reverse the elements of the 1D array using slicing.
import numpy as np
arr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
reversed_arr = arr[::-1]
print(reversed_arr)

[1 2 3 4]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
'''
Part 3: Array Operations
6. Array Arithmetic:
o Create another 1D array of 10 integers between 1 and 10.
o Perform the following element-wise operations between the 1D arrays created in Part 1 and Part 3:
▪ Addition
▪ Multiplication
▪ Subtract a constant value (e.g., 5) from the array.
'''
#6. o Create another 1D array of 10 integers between 1 and 10.
# import numpy as np
# arr = np.array([1,2,3,4,5,6,7,8,9,10])
# print(arr)
# import numpy as np
# arr = np.random.randint(1, 10, 9)
# print(arr)


#o Perform the following element-wise operations between the 1D arrays created in Part 1 and Part 3:
# ▪ Addition
# ▪ Multiplication
# ▪ Subtract a constant value (e.g., 5) from the array

import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6,7, 8])
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
power = arr1 ** 2
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Power (arr1 squared):", power)




Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Power (arr1 squared): [ 1  4  9 16]


In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1 2 3 4]


In [ ]:
'''
Part 4: Random Number Generation and Copying
7. Random Numbers:
o Create a 1D array of 5 random values between 0 and 1.
o o Create another 1D array of 5 random values between -1 and 1.

'''
#o Create a 1D array of 5 random values between 0 and 1.
import numpy as np
arr = np.random.rand(5)
print(arr)


#o Create another 1D array of 5 random values between -1 and 1.
import numpy as np
arr = np.random.uniform(-1, 1, 5)
print(arr)

[0.16007822 0.26628948 0.38035321 0.69533695 0.31297847]
[-0.68375362  0.12833049 -0.10538635  0.80024204  0.01012498]


In [ ]:
'''
8. Copy vs View:
o Create a copy of the original 2D array from Part 1.
o Modify one element in the copy and show that it doesn’t affect the
original array.
o Create a view of the original 2D array and modify one element.
Show that it does affect the original array.

# '''
#o Create a copy of the original 2D array from Part 1.
import numpy as np
arr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_copy = arr.copy()
print(arr_copy)

#o Modify one element in the copy and show that it doesn’t affect the original array
import numpy as np
array = np.array([1, 2, 3, 4, 5])

copy_array = array.copy()
view_array = array[1:]
# Modify an element in the copy
copy_array[0] = 10

# Modify an element in the view
view_array[0] = 20

print("Copy array:", copy_array)
print("View array:", view_array)

#o Create a view of the original 2D array and modify one element. Show that it does affect the original array
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a view (slice) of the original array
view_array = array[0:2, :]

# Modify an element in the view
view_array[1, 0] = 10

print("\nView Array:")
print(view_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Copy array: [10  2  3  4  5]
View array: [20  3  4  5]

View Array:
[[ 1  2  3]
 [10  5  6]]


In [ ]:
'''
Part 5: Bonus
9. Challenge Task:
o Write a program that asks the user to input a number (n), and then
generates an n x n array of random integers between 1 and 100.
o Find the sum of all the elements in the array and print the result.
'''

#o Write a program that asks the user to input a number (n), and then generates an n x n array of random integers between 1 and 100.
import numpy as np

array = np.random.randint(1, 101, size=(5, 5))

print(array)

'''import numpy as np
n = int(input("Enter the size of the array: "))
array = np.random.randint(1, 101, (n, n))

print(array)'''

#o Find the sum of all the elements in the array and print the result.
import numpy as np
array = np.random.randint(1, 101, size=(5, 5))
sum = np.sum(array)
print("Sum of all elements in the array:", sum)

[[ 10  41  76  85  80]
 [ 30 100  44  82  43]
 [ 17  88  24  67  62]
 [  2   4  78  43  41]
 [ 45  33  98  73  14]]
Sum of all elements in the array: 1109
